In [98]:
%matplotlib inline
import numpy as np
import pandas as pd
import scipy
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
import re
import spacy
from collections import Counter

from sklearn import ensemble
from sklearn.model_selection import train_test_split

from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LogisticRegression

from sklearn.svm import SVC
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import Normalizer

In [2]:
from nltk.corpus import gutenberg, stopwords

In [42]:
# Utility function to clean text.
def text_cleaner(text, pattern1, pattern2):
    
    # Visual inspection shows spaCy does not recognize the double dash '--'.
    # Better get rid of it now!
    text = re.sub(r'--',' ',text)
    
    # Get rid of headings in square brackets.
    text = re.sub("[\[].*?[\]]", "", text)
    
    # Get rid of chapter titles.
    text = re.sub(pattern1,'',text)
    text = re.sub(pattern2,'',text)
    
    # Get rid of extra whitespace.
    text = ' '.join(text.split())
    
    text = text.lower()
    
    return text

In [43]:
caesar = gutenberg.raw('shakespeare-caesar.txt')
hamlet = gutenberg.raw('shakespeare-hamlet.txt')
macbeth = gutenberg.raw('shakespeare-macbeth.txt')

caesar = text_cleaner(caesar, r'Actus .*', r'Scoena .*')
hamlet = text_cleaner(hamlet, r'Actus .*', r'Scoena .*')
macbeth = text_cleaner(macbeth, r'Actus .*', r'Scoena .*')

In [24]:
nlp = spacy.load('en')

In [45]:
caesar_doc = nlp(caesar)

In [46]:
hamlet_doc = nlp(hamlet)

In [47]:
macbeth_doc = nlp(macbeth)

In [37]:
# Utility function to calculate how frequently words appear in the text.
def word_frequencies(text, include_stop=False):
    
    # Build a list of words.
    # Strip out punctuation and, optionally, stop words.
    words = []
    for token in text:
        if not token.is_punct and (not token.is_stop or include_stop):
            words.append(token.text)
            
    # Build and return a Counter object containing word counts.
    return Counter(words)

In [48]:
caesar_freq = word_frequencies(caesar_doc, include_stop=False).most_common(10)
print('Caesar:', caesar_freq)

Caesar: [('caesar', 189), ('brutus', 161), ('bru', 153), ('haue', 147), ('shall', 125), ('thou', 115), ('cassi', 107), ('cassius', 85), ('antony', 75), ('come', 74)]


In [49]:
hamlet_freq = word_frequencies(hamlet_doc, include_stop=False).most_common(10)
print('Hamlet:', hamlet_freq)

Hamlet: [('ham', 337), ('lord', 211), ('haue', 175), ('king', 172), ("'s", 122), ('shall', 107), ('thou', 104), ('let', 104), ('come', 104), ('hamlet', 99)]


In [50]:
macbeth_freq = word_frequencies(macbeth_doc, include_stop=False).most_common(10)
print('Hamlet:', macbeth_freq)

Hamlet: [('macb', 137), ("'s", 131), ('haue', 122), ('thou', 87), ('enter', 81), ('shall', 68), ('macbeth', 61), ('thee', 61), ('vpon', 60), ('macd', 58)]


In [51]:
# Group into sentences.
caesar_sents = [[sent, "Caesar"] for sent in caesar_doc.sents]
hamlet_sents = [[sent, "Hamlet"] for sent in hamlet_doc.sents]
macbeth_sents = [[sent, "Macbeth"] for sent in macbeth_doc.sents]

In [53]:
# Combine the sentences from the two novels into one data frame.
sentences = pd.DataFrame(caesar_sents + macbeth_sents + macbeth_sents)
sentences.head()

0       1
0  (enter, flauius, ,, murellus, ,, and, certaine...  Caesar
1                                       (flauius, .)  Caesar
2  (hence, :, home, you, idle, creatures, ,, get,...  Caesar
3  (what, ,, know, you, not, (, being, mechanical...  Caesar
4  (you, ought, not, walke, vpon, a, labouring, d...  Caesar

In [54]:
# Utility function to create a list of the 2000 most common words.
def bag_of_words(text):
    
    # Filter out punctuation and stop words.
    allwords = [token.lemma_
                for token in text
                if not token.is_punct
                and not token.is_stop]
    
    # Return the most common words.
    return [item[0] for item in Counter(allwords).most_common(2000)]

In [57]:
bow_caesar = bag_of_words(caesar_doc)
bow_hamlet = bag_of_words(hamlet_doc)
bow_macbeth = bag_of_words(macbeth_doc)

In [58]:
common_words = set(bow_caesar + bow_hamlet + bow_macbeth)

In [60]:
# Each value is the count of the times the word appears in each sentence.
def bow_features(sentences, common_words):
    
    # Scaffold the data frame and initialize counts to zero.
    df = pd.DataFrame(columns=common_words)
    df['text_sentence'] = sentences[0]
    df['text_source'] = sentences[1]
    df.loc[:, common_words] = 0
    
    # Process each row, counting the occurrence of words in each sentence.
    for i, sentence in enumerate(df['text_sentence']):
        
        # Convert the sentence to lemmas, then filter out punctuation,
        # stop words, and uncommon words.
        words = [token.lemma_
                 for token in sentence
                 if (
                     not token.is_punct
                     and not token.is_stop
                     and token.lemma_ in common_words
                 )]
        
        # Populate the row with word counts.
        for word in words:
            df.loc[i, word] += 1
        
        # This counter is just to make sure the kernel didn't hang.
        if i % 500 == 0:
            print("Processing row {}".format(i))
            
    return df

In [61]:
# Create our data frame with features. This can take a while to run.
word_counts = bow_features(sentences, common_words)
word_counts.head()

Processing row 0
Processing row 500
Processing row 1000
Processing row 1500
Processing row 2000
Processing row 2500
Processing row 3000
Processing row 3500
Processing row 4000
Processing row 4500


vnrighteous taper cheere gaming stab'd flagon prophetique fly illusion  \
0           0     0      0      0      0      0           0   0        0   
1           0     0      0      0      0      0           0   0        0   
2           0     0      0      0      0      0           0   0        0   
3           0     0      0      0      0      0           0   0        0   
4           0     0      0      0      0      0           0   0        0   

  backward     ...     hew physick flye infect end rapier aboord bellow  \
0        0     ...       0       0    0      0   0      0      0      0   
1        0     ...       0       0    0      0   0      0      0      0   
2        0     ...       0       0    0      0   0      0      0      0   
3        0     ...       0       0    0      0   0      0      0      0   
4        0     ...       0       0    0      0   0      0      0      0   

                                       text_sentence text_source  
0  (enter, flauius, ,, murellus, ,, and, certaine...      Caesar  
1                                       (flauius, .)      Caesar  
2  (hence, :, home, you, idle, creatures, ,, get,...      Caesar  
3  (what, ,, know, you, not, (, being, mechanical...      Caesar  
4  (you, ought, not, walke, vpon, a, labouring, d...      Caesar  

[5 rows x 4014 columns]

### With Random Forest... the cross validation test scores range in the 0.85-0.88 range.

In [63]:
rfc = ensemble.RandomForestClassifier()
Y = word_counts['text_source']
X = np.array(word_counts.drop(['text_sentence','text_source'], 1))

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    Y,
                                                    test_size=0.4,
                                                    random_state=0)
train = rfc.fit(X_train, y_train)

print('Training set score:', rfc.score(X_train, y_train))
print('\nTest set score:', rfc.score(X_test, y_test))

Training set score: 0.980749398419

Test set score: 0.864948453608


In [65]:
scores = cross_val_score(rfc, X, Y, cv=5)
scores    

array([ 0.87641607,  0.85979381,  0.87216495,  0.8875129 ,  0.85758514])

### Also in a similiar range for Logistic Regression- this time 0.84-0.88.

In [84]:
lr = LogisticRegression(solver='newton-cg')
train = lr.fit(X_train, y_train)
print(X_train.shape, y_train.shape)
print('Training set score:', lr.score(X_train, y_train))
print('\nTest set score:', lr.score(X_test, y_test))

(2909, 4012) (2909,)
Training set score: 0.941216913029

Test set score: 0.867525773196


In [85]:
scores2 = cross_val_score(lr, X, Y, cv=5)
scores2

array([ 0.86096807,  0.84329897,  0.88041237,  0.875129  ,  0.84623323])

### The lowest scores so far for Gradient Boosting Classifier...

In [69]:
clf = ensemble.GradientBoostingClassifier()

train = clf.fit(X_train, y_train)

print('Training set score:', clf.score(X_train, y_train))
print('\nTest set score:', clf.score(X_test, y_test))

Training set score: 0.830525953936

Test set score: 0.812886597938


In [70]:
scores3 = cross_val_score(clf, X, Y, cv=5)
scores3 

array([ 0.81359423,  0.78041237,  0.83298969,  0.82765738,  0.78637771])

### Support Vector Machine did the best overall...

In [74]:
svm = SVC(kernel = 'linear')
svm.fit(X_train, y_train)

print('Training set score:', svm.score(X_train, y_train))
print('\nTest set score:', svm.score(X_test, y_test))

Training set score: 0.961155036095

Test set score: 0.865979381443


In [75]:
scores4 = cross_val_score(svm, X, Y, cv=5)
scores4 

array([ 0.87435633,  0.86597938,  0.88453608,  0.875129  ,  0.86377709])

### So Support Vector Machine did best overall. 

In [86]:
print("Random Forest: ", np.mean(scores))
print("Logistic Regression: ", np.mean(scores2))
print("Gradient Boosting Classifier: ", np.mean(scores3))
print("Support Vector Machine: ", np.mean(scores4))

Random Forest:  0.870694573603
Logistic Regression:  0.861208328692
Gradient Boosting Classifier:  0.808206276465
Support Vector Machine:  0.872755577269


In [91]:
#reading in the data, this time in the form of paragraphs
caesar_p = gutenberg.paras('shakespeare-caesar.txt')
hamlet_p = gutenberg.paras('shakespeare-hamlet.txt')
macbeth_p = gutenberg.paras('shakespeare-macbeth.txt')

shakespear_p = caesar_p + hamlet_p + macbeth_p
#processing
shakespear_paras=[]
for paragraph in shakespear_p:
    para=paragraph[0]
    #removing the double-dash from all words
    para=[re.sub(r'--','',word) for word in para]
    #Forming each paragraph into a string and adding it to the list of strings.
    shakespear_paras.append(' '.join(para))

print(shakespear_paras[0:4])

['[ The Tragedie of Julius Caesar by William Shakespeare 1599 ]', 'Actus Primus .', 'Enter Flauius , Murellus , and certaine Commoners ouer the Stage .', 'Flauius .']


In [97]:
X_train, X_test = train_test_split(shakespear_paras, test_size=0.4, random_state=0)

vectorizer = TfidfVectorizer(max_df=0.5, # drop words that occur in more than half the paragraphs
                             min_df=2, # only use words that appear at least twice
                             stop_words='english', 
                             lowercase=True, #convert everything to lower case (since Alice in Wonderland has the HABIT of CAPITALIZING WORDS for EMPHASIS)
                             use_idf=True,#we definitely want to use inverse document frequencies in our weighting
                             norm=u'l2', #Applies a correction factor so that longer paragraphs and shorter paragraphs get treated equally
                             smooth_idf=True #Adds 1 to all document frequencies, as if an extra document existed that used every word once.  Prevents divide-by-zero errors
                            )


#Applying the vectorizer
shakespear__paras_tfidf=vectorizer.fit_transform(shakespear_paras)
print("Number of features: %d" % shakespear__paras_tfidf.get_shape()[1])

#splitting into training and test sets
X_train_tfidf, X_test_tfidf= train_test_split(shakespear__paras_tfidf, test_size=0.4, random_state=0)


#Reshapes the vectorizer output into something people can read
X_train_tfidf_csr = X_train_tfidf.tocsr()

#number of paragraphs
n = X_train_tfidf_csr.shape[0]
#A list of dictionaries, one per paragraph
tfidf_bypara = [{} for _ in range(0,n)]
#List of features
terms = vectorizer.get_feature_names()
#for each paragraph, lists the feature words and their tf-idf scores
for i, j in zip(*X_train_tfidf_csr.nonzero()):
    tfidf_bypara[i][terms[j]] = X_train_tfidf_csr[i, j]

#Keep in mind that the log base 2 of 1 is 0, so a tf-idf score of 0 indicates that the word was present once in that sentence.
og_sentence_1 = X_train[5]
tf_idf_vector1 = tfidf_bypara[5]

print('Original sentence: ', og_sentence_1)
print('Tf_idf vector: ', tf_idf_vector1)

Number of features: 330
Original sentence:  Guild .
Tf_idf vector:  {'guild': 1.0}


In [110]:
X_train_tfidf_csr.get_shape()

(1423, 330)

In [111]:
len(shakespear_paras)

2372

In [102]:
#Our SVD data reducer.  We are going to reduce the feature space from 1379 to 130.
svd= TruncatedSVD(130)
lsa = make_pipeline(svd, Normalizer(copy=False))
# Run SVD on the training data, then project the training data.
X_train_lsa = lsa.fit_transform(X_train_tfidf)

variance_explained=svd.explained_variance_ratio_
total_variance = variance_explained.sum()
print("Percent variance captured by all components:",total_variance*100)

#Looking at what sorts of paragraphs our solution considers similar, for the first five identified topics
paras_by_component=pd.DataFrame(X_train_lsa,index=X_train)
for i in range(35,40):
    print('Component {}:'.format(i))
    print(paras_by_component.loc[:,i].sort_values(ascending=False)[0:10])

Percent variance captured by all components: 93.1159739067
Component 35:
Osr .     0.838335
Osr .     0.838335
Osr .     0.838335
Osr .     0.838335
Osr .     0.838335
Osr .     0.838335
Osr .     0.838335
Osr .     0.838335
Barn .    0.467084
Barn .    0.467084
Name: 35, dtype: float64
Component 36:
Por .    0.767166
Por .    0.767166
Por .    0.767166
Por .    0.767166
Por .    0.767166
Por .    0.767166
Por .    0.767166
Por .    0.767166
Osr .    0.007660
Osr .    0.007660
Name: 36, dtype: float64
Component 37:
Scena Sexta .      0.939481
Scena Septima .    0.938871
Scena Quarta .     0.910838
Scena Secunda .    0.865348
Scena Secunda .    0.865348
Scena Secunda .    0.865348
Scena Secunda .    0.865348
Scena Secunda .    0.865348
Scena Tertia .     0.800506
Scena Tertia       0.800506
Name: 37, dtype: float64
Component 38:
Thunder .                                                                 0.997595
Thunder .                                                                 0.9

In [103]:
paras_by_component

0    \
Exeunt .                                            8.929495e-16   
Enter Horatio , with an Attendant .                -5.026364e-12   
Exit Cinna .                                       -4.839970e-13   
Exeunt .                                            2.400817e-16   
Luc .                                              -4.622801e-19   
Guild .                                             9.861222e-17   
Macb .                                             -4.198454e-15   
Guil .                                              1.955625e-15   
I goe , and it is done : the Bell inuites me .     -2.593717e-13   
Hor .                                              -1.926744e-16   
Brut .                                             -5.546661e-18   
Thunder .                                           6.523794e-13   
Cassi .                                             3.086362e-16   
Mar .                                              -1.635069e-17   
Macb .                                             -4.198279e-15   
Decius .                                           -1.119088e-13   
Ham .                                               1.000000e+00   
Bru .                                              -6.511435e-15   
Rosin .                                             4.616085e-17   
Ham .                                               1.000000e+00   
Kin .                                              -3.350063e-15   
Banq .                                              1.483105e-18   
Old man .                                          -4.640304e-13   
Qu .                                                8.692107e-17   
Lenox .                                             2.167628e-13   
Guil .                                              1.953923e-15   
Ham .                                               1.000000e+00   
La .                                               -8.723158e-17   
Mar .                                              -1.659570e-17   
Enter Flauius , Murellus , and certaine Commone...  2.965863e-13   
...                                                          ...   
Clit .                                             -7.926456e-14   
Cas .                                               3.165544e-17   
Bru .                                              -6.511451e-15   
Ant .                                              -4.110290e-17   
Alarum .                                           -2.172604e-13   
Mar .                                              -1.659532e-17   
Macb .                                             -4.198441e-15   
3 .                                                -0.000000e+00   
Cask .                                              8.104782e-18   
Exeunt .                                            2.380161e-16   
Macb .                                             -4.198441e-15   
Fran .                                              1.762000e-13   
Polon .                                            -1.757710e-17   
Wife .                                             -6.677550e-16   
Rosse .                                             6.193540e-14   
Mac .                                               5.829568e-15   
Cas .                                               3.165544e-17   
1 .                                                -0.000000e+00   
Macd .                                             -4.168983e-17   
Macb .                                             -4.198441e-15   
Ant .                                              -4.110290e-17   
Sey .                                               5.433313e-16   
Banq .                                              1.478616e-18   
Banq .                                              1.478616e-18   
Art .                                               4.835564e-13   
King .                                             -1.319488e-14   
2 .                                                -0.000000e+00   
Mar .                                            